version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASS_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
